### ISSUE TITLE
demo crash

### ISSUE THREAD

**Issue by Gldkslfmsd** [vidraj/segmentace#6]
:(
```
(p3)machacek@victoria:/net/work/people/machacek/derinet/segmentace$ echo -e 'Ahoj světe !\nNáš začátek byl pomalejší , litoval po prohře Berdych .' | ./segment-by-derinet.py -a czech-morfflex-pdt-161115/czech-morfflex-pdt-161115.tagger derinet-1-4.tsv.gz
INFO from __main__ at 2017-11-13 21:55:26,201: Started.
INFO from segmentace at 2017-11-13 21:55:26,202: Loading derivations.
Traceback (most recent call last):
  File "./segment-by-derinet.py", line 66, in <module>
    segmenter = Segmentace(derinet_file_name, morfflex_file_name, morpho_file_name)
  File "/lnet/.nfs/spec/work/people/machacek/derinet/segmentace/segmentace.py", line 203, in __init__
    derinet_db = DeriNetDatabase(derinet_file_name)
  File "/lnet/.nfs/spec/work/people/machacek/derinet/segmentace/segmentace.py", line 102, in __init__
    for lexeme in derinet:
  File "/lnet/.nfs/spec/work/people/machacek/derinet/segmentace/segmentace.py", line 85, in __next__
    return self.next()
  File "/lnet/.nfs/spec/work/people/machacek/derinet/segmentace/segmentace.py", line 91, in next
    id, lemma, techlemma, pos, parent = line.split('\t')
ValueError: too many values to unpack (expected 5)
```
There was this bug, but I think I fixed it. See my pull request soon. :)

**Comment by vidraj** [comment]
Confirmed. The issue is that the downloaded DeriNet database comes from the DeriSearch query engine, which has started using additional annotation recently. That confuses the parser.

Ignoring the unexpected values is certainly a way of solving this, but I see a better one – namely downloading the correct, unmodified files from the master repository at ÚFAL. I'll submit a patch in a few minutes.
