### ISSUE TITLE
make download doesn't fetch derinet

### ISSUE THREAD

**Issue by Gldkslfmsd** [vidraj/segmentace#8]
Hello!

```
d@e:~/tmp$ git clone https://github.com/vidraj/segmentace.git
Cloning into 'segmentace'...
remote: Counting objects: 164, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 164 (delta 19), reused 28 (delta 17), pack-reused 131
Receiving objects: 100% (164/164), 48.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (93/93), done.
Checking connectivity... done.
d@e:~/tmp$ cd segmentace/
d@e:~/tmp/segmentace$ make download
wget -O "czech-morfflex-pdt-161115.zip" 'https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-1836/czech-morfflex-pdt-161115.zip?sequence=1&isAllowed=y'
--2017-11-14 18:38:48--  https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-1836/czech-morfflex-pdt-161115.zip?sequence=1&isAllowed=y
Překládám lindat.mff.cuni.cz (lindat.mff.cuni.cz)… 195.113.20.140
Navazuje se spojení s lindat.mff.cuni.cz (lindat.mff.cuni.cz)|195.113.20.140|:443… spojeno.
HTTP požadavek odeslán, program čeká na odpověď… 200 OK
Délka: 72538619 (69M) [application/zip]
Ukládám do: „czech-morfflex-pdt-161115.zip“

100%[======================================>] 72 538 619  3,24MB/s   za 23s    

2017-11-14 18:39:11 (3,03 MB/s) – „czech-morfflex-pdt-161115.zip“ uloženo [72538619/72538619]

unzip -DD "czech-morfflex-pdt-161115.zip"
Archive:  czech-morfflex-pdt-161115.zip
   creating: czech-morfflex-pdt-161115/
  inflating: czech-morfflex-pdt-161115/README.html  
  inflating: czech-morfflex-pdt-161115/README  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-pdt-161115-no_dia-pos_only.tagger  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-pdt-161115-pos_only.tagger  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-161115-no_dia.dict  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-pdt-161115.tagger  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-161115-no_dia-pos_only.dict  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-161115.dict  
  inflating: czech-morfflex-pdt-161115/LICENSE  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-161115-pos_only.dict  
  inflating: czech-morfflex-pdt-161115/czech-morfflex-pdt-161115-no_dia.tagger
```

```
d@e:~/tmp/segmentace$ echo ahoj světe | ./segment-by-derinet.py -a czech-morfflex-pdt-161115/czech-morfflex-pdt-161115.tagger derinet-1-4.tsv.gz
INFO from __main__ at 2017-11-14 18:42:38,362: Started.
INFO from segmentace at 2017-11-14 18:42:38,363: Loading derivations.
Traceback (most recent call last):
  File "./segment-by-derinet.py", line 66, in <module>
    segmenter = Segmentace(derinet_file_name, morfflex_file_name, morpho_file_name)
  File "/home/d/tmp/segmentace/segmentace.py", line 203, in __init__
    derinet_db = DeriNetDatabase(derinet_file_name)
  File "/home/d/tmp/segmentace/segmentace.py", line 101, in __init__
    with DeriNetParser(derinet_file_name) as derinet:
  File "/home/d/tmp/segmentace/segmentace.py", line 75, in __enter__
    self.filehandle = gzip.open(self.filename, "rt", newline='\n')
  File "/usr/lib/python3.4/gzip.py", line 52, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.4/gzip.py", line 181, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'derinet-1-4.tsv.gz'
```

There seems to be a bug in Makefile. Of course I can avoid it and download derinet manually, but that's not convenient and consistent with README...

**Comment by vidraj** [comment]
Works for me.

What does `make -rnd download` and `make -rnd derinet-1-4.tsv.gz` say?

**Comment by Gldkslfmsd** [comment]
```
d@e:~/tmp/segmentace$ make -rnd download
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
Čtou se makefily…
Reading makefile `Makefile'...
Soubory makefile se aktualizují…
 Considering target file `Makefile'.
  Looking for an implicit rule for `Makefile'.
  No implicit rule found for `Makefile'.
  Finished prerequisites of target file `Makefile'.
 No need to remake target `Makefile'.
Aktualizují se cíle…
Considering target file `download'.
 File `download' does not exist.
  Considering target file `czech-morfflex-pdt-161115/README'.
    Considering target file `czech-morfflex-pdt-161115.zip'.
     Finished prerequisites of target file `czech-morfflex-pdt-161115.zip'.
    No need to remake target `czech-morfflex-pdt-161115.zip'.
   Finished prerequisites of target file `czech-morfflex-pdt-161115/README'.
   Prerequisite `czech-morfflex-pdt-161115.zip' is older than target `czech-morfflex-pdt-161115/README'.
  No need to remake target `czech-morfflex-pdt-161115/README'.
 Finished prerequisites of target file `download'.
Must remake target `download'.
Successfully remade target file `download'.
make: Nothing to be done for `download'.
d@e:~/tmp/segmentace$  make -rnd derinet-1-4.tsv.gz
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
Čtou se makefily…
Reading makefile `Makefile'...
Soubory makefile se aktualizují…
 Considering target file `Makefile'.
  Looking for an implicit rule for `Makefile'.
  No implicit rule found for `Makefile'.
  Finished prerequisites of target file `Makefile'.
 No need to remake target `Makefile'.
Aktualizují se cíle…
Considering target file `derinet-1-4.tsv.gz'.
 File `derinet-1-4.tsv.gz' does not exist.
 Looking for an implicit rule for `derinet-1-4.tsv.gz'.
 No implicit rule found for `derinet-1-4.tsv.gz'.
 Finished prerequisites of target file `derinet-1-4.tsv.gz'.
Must remake target `derinet-1-4.tsv.gz'.
make: *** No rule to make target `derinet-1-4.tsv.gz'. Konec.
d@e:~/tmp/segmentace$
```

**Comment by vidraj** [comment]
I assume your Makefile is really identical to the current master HEAD. In that case, it might be a bug caused by different Make versions. I have GNU Make 4.2.1, yours is older.

If you run `make --warn-undefined-variables download`, does it complain that `$(DERINET)` is undefined? If so, try updating your Make.

**Comment by Gldkslfmsd** [comment]
yes, it complains.

I don't want to update my Make just because of this, downloading it manually is easier for me. I suggest you to replace downloading with a simple bash script or commands to copypaste. That would work for everyone...

**Comment by vidraj** [comment]
Maintaining an extra script would be too difficult, the script and the Makefile would drift out of sync too fast. Maintaining a single-source-of-truth for both would require a byzantine system of configures. The names of the necessary data files are mentioned in the Makefile explicitly and I believe that this is enough.

An alternative would be to replace the POSIX-compatible `::=` simple expansion operators with the GNU-specific `:=`, or to deparametrize the Makefile and just copy the content of the variables everywhere. I am not going to do any of those.

I'll update the dependency list to make it clear that GNU Make 4.0 or newer is required.
